# -*- coding: utf-8 -*-
"""Hashing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aKmkBu_suibXutXeKuynPNAVPtSjiTXo
"""

import hashlib
ins = input('what do you want to hash : ')
hashing = hashlib.md5(ins.encode())
print(('hashed string : ')+(hashing.hexdigest()))